### PR TITLE
change owernship to defined user

### PR DESCRIPTION
**Pull request by bcg62**
addressing issue #2

### CODE REVIEW

**Comment by vaskas** [comment]
Thanks!

**Comment by bcg62** [comment]
@vaskas thanks for accepting! - can you bump and push the new version to the supermarket?

**Comment by vaskas** [comment]
@bcg62 I've added you as a collaborator both on github and supermarket. Please feel free to push the new version.

**Comment by bcg62** [comment]
@vaskas awesome thanks!

**Pull request merged**
